# Generated by Django 2.0.9 on 2018-10-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='product_name',
            new_name='shipper_name',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='suppliermodel',
            name='product',
        ),
        migrations.AddField(
            model_name='supplier',
            name='product',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='suppliermodel',
            name='shipper',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
